name: Build and deploy PyData Osaka Sphinx site
on:
  push:
    branches:
    - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: "main"

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U Sphinx
        pip install -r requirements.txt
        
    - name: Build Sphinx
      run: |
        mkdir builddir
        sphinx-build -b html sourcedir builddir
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./builddir
